### ISSUE TITLE
Scheduler to clean old projects

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#10575]
See the current property: https://github.com/jhipster/jhipster-lite/blob/main/src/main/resources/config/application-cloud.yml#L1-L2

We should add new properties:
```
application:
  clean:
    forced-project-folder: /tmp/jhlite
    older-in-hours: 24
    scheduler: 'xxxx'
```

So when scheduler is running, it will check all projects in `/tmp/jhlite`
If the project is older than the property (here 24h), it will be deleted

It is needed to clean old generated projects in cloud instance

important: this behavior should be disabled by default
