### ISSUE TITLE
Align JHLite properties

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#11104]
There are several properties, related to JHLite project:

```yaml
jhlite-hidden-resources:
  slugs:
    - svelte-core

jhlite-preset-file:
  name: preset.json

application:
  forced-project-folder: /tmp/jhlite
```

It should be rework to be under the same root key `jhlite.*`

Self assigned to work on this.

Wonder if it will impact your jhlite custom, @murdos ?
