### ISSUE TITLE
Gradle CI doesn't launch unit tests

### ISSUE THREAD

**Issue by fabienpuissant** [jhipster/jhipster-lite#11513]
It seems that the gradle ci don't launch unit test only IT.

I have tried to put a failing unit test and the ci was green 

Is this the behaviour or a misconfiguration on my side ?

A possible working solution

**github-actions.yml**

```
jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: 'Setup: checkout project'
        uses: actions/checkout@v4
      - name: 'Setup: environment'
        id: setup
        uses: ./.github/actions/setup
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: 'Test: run unit tests'
        run: ./gradlew clean test --no-daemon
      - name: 'Test: run integration tests'
        run: ./gradlew clean integrationTest --no-daemon
```
