### ISSUE TITLE
Codecov configuration

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/jhipster-lite#744]
Add codecov.yml at root of the project:

```yaml
coverage:
  status:
    project:
      default:
        target: "100%"
    patch:
      enabled: false
```
